USE RaPizzDB;

DROP TABLE IF EXISTS Garnir;
DROP TABLE IF EXISTS Comporter;
DROP TABLE IF EXISTS Ingredient;
DROP TABLE IF EXISTS Pizza;
DROP TABLE IF EXISTS Livraison;
DROP TABLE IF EXISTS Livreur;
DROP TABLE IF EXISTS Client;
DROP TABLE IF EXISTS Adresse;
DROP TABLE IF EXISTS Vehicule;
